## Plugins ##
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux#v0.2'

## Setup ##
set -sg escape-time 50
set-option -sa terminal-overrides ",xterm*:Tc"
set -g terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[5 q'
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
unbind C-b
set -g prefix C-Space
bind C-space send-prefix
set -g @yank_selection_mouse 'clipboard'
set -g set-clipboard on
set -g mouse on
set -g mode-keys vi

## Bindings ##
bind -n S-Left select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up select-pane -U
bind -n S-Down select-pane -D
bind -n C-Left split-window -hb -c '#{pane_current_path}'
bind -n C-Right split-window -h -c '#{pane_current_path}'
bind -n C-Up split-window -vb -c '#{pane_current_path}'
bind -n C-Down split-window -v -c '#{pane_current_path}'
bind -n C-Left previous-window
bind -n C-Right next-window
bind '_' split-window -v -c '#{pane_current_path}'
bind '"' split-window -h -c '#{pane_current_path}'
bind 'r' respawn-pane -k
bind S-r source-file '$HOME/.config/tmux/tmux.conf'

## Theme ##
set -g @catppuccin_window_left_separator ' '
set -g @catppuccin_window_right_separator ''
set -g @catppuccin_window_middle_separator ' | '
set -g @catppuccin_window_default_fill 'none'
set -g @catppuccin_window_default_text '#W'
set -g @catppuccin_window_current_fill 'all'
set -g @catppuccin_window_current_text '#W'
set -g @catppuccin_status_modules_right 'directory user session'
set -g @catppuccin_status_left_separator ''
set -g @catppuccin_status_right_separator '█'
set -g @catppuccin_status_connect_separator 'yes'

## Plugins setup ##
set -g @resurrect-processes '"btop -p 0" lf lazydocker'
run '$HOME/.config/tmux/plugins/tpm/tpm' # !keep as last line!
